---
# tasks file for tomcat

- name: install pip3
  apt: name=python3-pip state=present 
  
- name: Install lxml
  pip: name=lxml

- name: download tomcat server packages
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
    dest: /usr/local

- name: extract tomcat packages
  unarchive:
    src: /usr/local/apache-tomcat-10.0.27.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Copy the war file
  copy:
    src: ./target/hello-world-war-1.0.0.war
    dest: /usr/local/apache-tomcat-10.0.27/webapps/
    remote_src: yes

  
